Repository fluencelabs/nox, pull requests merged in 2018-12, with the labels that each got.

#301 Vm bencher
  bench/vm/.gitignore
  bench/vm/bencher/BenchTestGenerator.py
  bench/vm/bencher/TestDescriptor.py
  bench/vm/bencher/VMDescriptor.py
  bench/vm/bencher/WasmVMBencher.py
  bench/vm/bencher/main.py
  bench/vm/bencher/settings.py
  bench/vm/results/asmble.csv
  bench/vm/results/life.csv
  bench/vm/results/wasmer.csv
  bench/vm/results/wasmi.csv
  bench/vm/results/wavm.csv
Labels: research

#297 Validator for WASM code (draft)
  cli/Cargo.toml
  cli/README.md
  cli/clippy.toml
  cli/rust-toolchain
  cli/src/check.rs
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/utils.rs
  cli/src/whitelist.rs
  vm/examples/llamadb/Cargo.toml
  vm/examples/llamadb/src/main/rust/lib.rs
Labels: ~CLI

#299 Vm benchmark tests
  bench/vm/tests/README.md
  bench/vm/tests/compression/Cargo.toml
  bench/vm/tests/compression/rust-toolchain
  bench/vm/tests/compression/src/lib.rs
  bench/vm/tests/compression/src/settings.rs
  bench/vm/tests/factorization_reikna/Cargo.toml
  bench/vm/tests/factorization_reikna/rust-toolchain
  bench/vm/tests/factorization_reikna/src/lib.rs
  bench/vm/tests/factorization_reikna/src/settings.rs
  bench/vm/tests/fibonacci_bigint/Cargo.toml
  bench/vm/tests/fibonacci_bigint/rust-toolchain
  bench/vm/tests/fibonacci_bigint/src/lib.rs
  bench/vm/tests/fibonacci_bigint/src/settings.rs
  bench/vm/tests/matrix_product/Cargo.toml
  bench/vm/tests/matrix_product/rust-toolchain
  bench/vm/tests/matrix_product/src/lib.rs
  bench/vm/tests/matrix_product/src/settings.rs
  bench/vm/tests/matrix_qr_decomposition/Cargo.toml
  bench/vm/tests/matrix_qr_decomposition/rust-toolchain
  bench/vm/tests/matrix_qr_decomposition/src/lib.rs
  bench/vm/tests/matrix_qr_decomposition/src/settings.rs
  bench/vm/tests/matrix_svd_decomposition/Cargo.toml
  bench/vm/tests/matrix_svd_decomposition/rust-toolchain
  bench/vm/tests/matrix_svd_decomposition/src/lib.rs
  bench/vm/tests/matrix_svd_decomposition/src/settings.rs
  bench/vm/tests/recursive_hash/Cargo.toml
  bench/vm/tests/recursive_hash/rust-toolchain
  bench/vm/tests/recursive_hash/src/lib.rs
  bench/vm/tests/recursive_hash/src/settings.rs
Labels: research

#300 Master node status
  .travis.yml
  build.sbt
  ethclient/src/main/resources/reference.conf
  externalstorage/src/main/scala/fluence/swarm/SwarmClient.scala
  externalstorage/src/main/scala/fluence/swarm/responses/Manifest.scala
  node/src/main/resources/docker/entrypoint.sh
  node/src/main/resources/reference.conf
  node/src/main/scala/fluence/node/Configuration.scala
  node/src/main/scala/fluence/node/MasterNode.scala
  node/src/main/scala/fluence/node/MasterNodeApp.scala
  node/src/main/scala/fluence/node/NodeConfig.scala
  node/src/main/scala/fluence/node/StatusAggregator.scala
  node/src/main/scala/fluence/node/SwarmConfig.scala
  node/src/main/scala/fluence/node/config/MasterConfig.scala
  node/src/main/scala/fluence/node/docker/DockerIO.scala
  node/src/main/scala/fluence/node/eth/DeployerContract.scala
  node/src/main/scala/fluence/node/eth/DeployerContractConfig.scala
  node/src/main/scala/fluence/node/eth/EthereumRPCConfig.scala
  node/src/main/scala/fluence/node/solvers/Solver.scala
  node/src/main/scala/fluence/node/solvers/SolverHealth.scala
  node/src/main/scala/fluence/node/solvers/SolverInfo.scala
  node/src/main/scala/fluence/node/solvers/SolverParams.scala
  node/src/main/scala/fluence/node/solvers/SolverResponse.scala
  node/src/main/scala/fluence/node/solvers/SolversPool.scala
  node/src/main/scala/fluence/node/tendermint/ClusterData.scala
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
  project/SbtCommons.scala
  tools/node/docker-compose.yml
Labels: ~consensus

#305 WebAssembly VM benchmark results
  bench/vm/README.md
  bench/vm/bencher/TestDescriptor.py
  bench/vm/bencher/VMDescriptor.py
  bench/vm/results/asmble.csv
  bench/vm/results/data/asmble.csv
  bench/vm/results/data/life.csv
  bench/vm/results/data/wagon.csv
  bench/vm/results/data/wasmer.csv
  bench/vm/results/data/wasmi.csv
  bench/vm/results/data/wavm.csv
  bench/vm/results/images/compressions.png
  bench/vm/results/images/computations.png
  bench/vm/results/images/matrices.png
  bench/vm/results/life.csv
  bench/vm/results/result_analysis.ipynb
  bench/vm/results/wasmer.csv
  bench/vm/results/wasmi.csv
  bench/vm/results/wavm.csv
  bench/vm/tests/README.md
Labels: research

#306 remove old config from solver
  statemachine/docker/solver/run.sh
  statemachine/docker/solver/sm.config
  statemachine/src/main/resources/reference.conf
Labels: enhancement

#303 Collect network state from smart contract via CLI
  bootstrap/contracts/Deployer.sol
  bootstrap/test/TestDeployer.js
  cli/Cargo.toml
  cli/src/contract_status/cluster.rs
  cli/src/contract_status/code.rs
  cli/src/contract_status/mod.rs
  cli/src/contract_status/node.rs
  cli/src/contract_status/status.rs
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/status.rs
  cli/src/types.rs
  cli/src/utils.rs
  ethclient/src/main/java/fluence/ethclient/Deployer.java
  externalstorage/src/main/scala/fluence/swarm/SwarmClient.scala
  node/src/main/scala/fluence/node/MasterNodeApp.scala
  node/src/main/scala/fluence/node/StatusAggregator.scala
Labels: ~consensus

#307 Network contract
  .travis.yml
  bootstrap/contracts/Deployer.sol
  bootstrap/contracts/Network.sol
  bootstrap/migrations/2_contract_deploy.js
  bootstrap/package.json
  bootstrap/scripts/compile_sol.js
  bootstrap/scripts/generate_java_wrapper.sh
  bootstrap/scripts/swarm-simulation.js
  bootstrap/test/FluenceContractTest.js
  cli/README.md
  cli/src/contract_status/mod.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/utils.rs
  cli/src/whitelist.rs
  ethclient/src/main/java/fluence/ethclient/Network.java
  ethclient/src/main/resources/reference.conf
  ethclient/src/main/scala/fluence/ethclient/EthClient.scala
  ethclient/src/main/scala/fluence/ethclient/EthClientApp.scala
  ethclient/src/main/scala/fluence/ethclient/helpers/JavaRxToFs2.scala
  ethclient/src/test/scala/fluence/ethclient/ClusterContractSpec.scala
  node/README.md
  node/src/main/resources/reference.conf
  node/src/main/scala/fluence/node/AddCodeApp.scala
  node/src/main/scala/fluence/node/Configuration.scala
  node/src/main/scala/fluence/node/MasterNode.scala
  node/src/main/scala/fluence/node/MasterNodeApp.scala
  node/src/main/scala/fluence/node/config/MasterConfig.scala
  node/src/main/scala/fluence/node/eth/FluenceContract.scala
  node/src/main/scala/fluence/node/eth/FluenceContractConfig.scala
  node/src/main/scala/fluence/node/solvers/CodeManager.scala
  node/src/main/scala/fluence/node/tendermint/ClusterData.scala
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
  project/SbtCommons.scala
  tools/node/docker-compose.yml
  tools/node/single-master.yml
Labels: enhancement, tech debt

#311 enable cargo fmt
  .travis.yml
Labels: enhancement, tech debt, ~general

#310 Add Ethereum address to Node, BusyCluster and Code
  bootstrap/contracts/Deployer.sol
  bootstrap/contracts/Network.sol
  bootstrap/test/FluenceContractTest.js
  cli/src/contract_status/status.rs
  ethclient/src/main/java/fluence/ethclient/Network.java
  ethclient/src/test/scala/fluence/ethclient/ClusterContractSpec.scala
  node/src/main/scala/fluence/node/eth/FluenceContract.scala
Labels: ~general

#314 Python client deleted
  py-client/README.md
  py-client/codec.py
  py-client/dataengine.py
  py-client/example/client_identity.py
  py-client/example/query_counter.py
  py-client/example/query_llamadb.py
  py-client/misc_utils.py
  py-client/requirements.txt
  py-client/tmrpc.py
  py-client/verify.py
Labels: tech debt

#309 Update run scripts
  tools/node/docker-compose.yml
  tools/node/single-master.yml
  tools/run/README.md
  tools/run/blockchain.sh
  tools/run/cleanup.sh
  tools/run/compose.sh
  tools/run/linux/docker-compose.yml
  tools/run/linux/up.sh
  tools/run/macos/docker-compose.yml
Labels: enhancement

#315 Fix last port usage and refactor matchWork
  bootstrap/contracts/Deployer.sol
  bootstrap/contracts/Network.sol
  bootstrap/test/FluenceContractTest.js
  ethclient/src/main/java/fluence/ethclient/Network.java
Labels: enhancement, ~general

#316 Master node status in Fluence monitoring
  monitoring/.npmignore
  monitoring/README.md
  monitoring/package.json
  monitoring/src/abi.ts
  monitoring/src/code.ts
  monitoring/src/contractStatus.ts
  monitoring/src/fluence.ts
  monitoring/src/node.ts
  monitoring/src/nodeAddress.ts
  monitoring/src/nodeStatus.ts
  monitoring/tsconfig.json
  monitoring/webpack.config.js
  node/src/main/scala/fluence/node/StatusAggregator.scala
  tools/run/linux/docker-compose.yml
  tools/run/macos/docker-compose.yml
Labels: enhancement, ~general

#318 Sign transactions in CLI
  bootstrap/contracts/Deployer.sol
  bootstrap/scripts/compile_sol.js
  bootstrap/scripts/generate_java_wrapper.sh
  bootstrap/test/FluenceContractTest.js
  cli/Cargo.toml
  cli/src/contract_func.rs
  cli/src/contract_status/cluster.rs
  cli/src/contract_status/code.rs
  cli/src/contract_status/mod.rs
  cli/src/contract_status/node.rs
  cli/src/contract_status/status.rs
  cli/src/credentials.rs
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/utils.rs
  cli/src/whitelist.rs
  ethclient/src/main/java/fluence/ethclient/Network.java
  ethclient/src/test/scala/fluence/ethclient/ClusterContractSpec.scala
  node/src/main/resources/docker/entrypoint.sh
  node/src/main/scala/fluence/node/AddCodeApp.scala
  node/src/main/scala/fluence/node/MasterNodeApp.scala
  node/src/main/scala/fluence/node/StatusAggregator.scala
  node/src/main/scala/fluence/node/config/MasterConfig.scala
  node/src/main/scala/fluence/node/eth/FluenceContract.scala
  node/src/main/scala/fluence/node/solvers/SolverImage.scala
  node/src/main/scala/fluence/node/solvers/SolverInfo.scala
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
  tools/run/cleanup.sh
  tools/run/compose.sh
  tools/run/docker-compose.yml
  tools/run/linux/up.sh
  tools/run/macos/docker-compose.yml
Labels: ~CLI

#319 hot fix cli
  cli/src/publisher.rs
  cli/src/register.rs
Labels: ~CLI

#321 remove env from bash script headers
  node/src/main/resources/docker/entrypoint.sh
  vm/examples/run_example.sh
Labels: enhancement

#322 Deploy script
  bootstrap/package-lock.json
  bootstrap/package.json
  bootstrap/unlock-keys.js
  cli/Cargo.toml
  cli/src/main.rs
  cli/src/register.rs
  tools/run/compose.sh
  tools/run/node.yml
  tools/run/parity.yml
  tools/run/swarm.yml
Labels: ~CLI

#320 VM examples decoupling
  build.sbt
  node/README.md
  node/src/main/resources/docker/entrypoint.sh
  node/src/main/resources/docker/vmcode/vmcode-llamadb/llama_db.wasm
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
  project/SbtCommons.scala
  statemachine/docker/examples/.gitignore
  statemachine/docker/examples/vmcode-llamadb/llama_db.wasm
  statemachine/src/main/scala/fluence/statemachine/ServerRunner.scala
  statemachine/src/main/scala/fluence/statemachine/error/StateMachineError.scala
  vm/examples/README.md
  vm/examples/counter/Cargo.toml
  vm/examples/counter/rust-toolchain
  vm/examples/counter/src/counter.rs
  vm/examples/counter/src/lib.rs
  vm/examples/counter/src/main/rust/counter.rs
  vm/examples/counter/src/main/scala/fluence/vm/examples/CounterRunner.scala
  vm/examples/llamadb/Cargo.toml
  vm/examples/llamadb/rust-toolchain
  vm/examples/llamadb/src/lib.rs
  vm/examples/llamadb/src/main/scala/fluence/vm/examples/LlamaDbRunner.scala
  vm/examples/llamadb/src/tests.rs
  vm/src/main/resources/reference.conf
Labels: enhancement

#323 get rid of docker in build
  .travis.yml
  bench/vm/tests/README.md
  project/SbtCommons.scala
  vm/examples/README.md
Labels: enhancement

#317 Implement code pinning & node "privatization" mechanics in contract
  bootstrap/contracts/Deployer.sol
  bootstrap/contracts/Network.sol
  bootstrap/package.json
  bootstrap/test/FluenceContractTest.js
  cli/README.md
  cli/src/contract_status/app.rs
  cli/src/contract_status/cluster.rs
  cli/src/contract_status/mod.rs
  cli/src/contract_status/node.rs
  cli/src/contract_status/status.rs
  cli/src/publisher.rs
  cli/src/register.rs
  ethclient/src/main/java/fluence/ethclient/Network.java
  ethclient/src/main/scala/fluence/ethclient/helpers/Web3jConverters.scala
  ethclient/src/test/scala/fluence/ethclient/ClusterContractSpec.scala
  node/src/main/scala/fluence/node/config/MasterConfig.scala
  node/src/main/scala/fluence/node/eth/FluenceContract.scala
  node/src/main/scala/fluence/node/tendermint/ClusterData.scala
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
  project/build.properties
Labels: ~general
