Repository fluencelabs/nox, pull requests merged in 2018-10, with the labels that each got.

#200 Session enhancement
  build.sbt
  js-client/package.json
  js-client/src/Client.ts
  js-client/src/Engine.ts
  js-client/src/Result.ts
  js-client/src/ResultAwait.ts
  js-client/src/Session.ts
  js-client/src/SessionConfig.ts
  js-client/src/Signer.ts
  js-client/src/TendermintClient.ts
  js-client/src/examples/CustomCommands.ts
  js-client/src/examples/IncrementAndMultiply.ts
  js-client/src/main.ts
  js-client/src/responses.ts
  js-client/src/tx.ts
  js-client/src/utils.ts
  js-client/tendermint.d.ts
  js-client/tsconfig.json
  js-client/verify.md
  statemachine/src/main/scala/fluence/statemachine/tx/SessionSummary.scala
  statemachine/src/main/scala/fluence/statemachine/tx/TransactionStatus.scala
  statemachine/src/main/scala/fluence/statemachine/util/Crypto.scala
  statemachine/src/main/scala/fluence/statemachine/util/HexCodec.scala
Labels: ~consensus

#205 Db on pointers
  build.sbt
  js-client/README.md
  js-client/src/Result.ts
  js-client/src/ResultAwait.ts
  js-client/src/Session.ts
  js-client/src/examples/DbClient.ts
  js-client/src/examples/DbOnPointers.ts
  js-client/src/examples/IncrementAndMultiply.ts
  js-client/src/examples/QuotationClient.ts
  js-client/webpack.config.js
  statemachine/src/main/scala/fluence/statemachine/ServerRunner.scala
  statemachine/src/main/scala/fluence/statemachine/tx/FunctionCallDescription.scala
Labels: ~browser client

#206 String parameters support
  vm/src/main/resources/reference.conf
  vm/src/main/scala/fluence/vm/AsmleWasmVm.scala
  vm/src/main/scala/fluence/vm/ModuleInstance.scala
  vm/src/main/scala/fluence/vm/VmError.scala
  vm/src/main/scala/fluence/vm/WasmVm.scala
  vm/src/main/scala/fluence/vm/WasmVmImpl.scala
  vm/src/main/scala/fluence/vm/config/VmConfig.scala
  vm/src/main/scala/fluence/vm/package.scala
  vm/src/test/resources/wast/bad-allocation-function.wast
  vm/src/test/resources/wast/no-getMemory.wast
  vm/src/test/resources/wast/simple-string-passing.wast
  vm/src/test/scala/fluence/vm/AsmleWasmVmSpec.scala
Labels: enhancement

#210 extended regex for arguments, tests for browser client, refactoring
  js-client/package.json
  js-client/src/Result.ts
  js-client/src/ResultAwait.ts
  js-client/src/Session.ts
  js-client/src/TendermintClient.ts
  js-client/src/examples/DbOnPointers.ts
  js-client/src/examples/QuotationClient.ts
  js-client/src/responses.ts
  js-client/src/test/responses.spec.ts
  js-client/src/test/result.spec.ts
  js-client/src/test/signer.spec.ts
  js-client/src/test/utils.spec.ts
  js-client/src/utils.ts
  statemachine/src/main/scala/fluence/statemachine/tx/FunctionCallDescription.scala
Labels: ~browser client, ~consensus

#216 EthClient with fs2
  build.sbt
  ethclient/src/main/scala/fluence/ethclient/EthClient.scala
  ethclient/src/main/scala/fluence/ethclient/EthClientApp.scala
  ethclient/src/main/scala/fluence/ethclient/helpers/JavaFutureConversion.scala
  ethclient/src/main/scala/fluence/ethclient/helpers/JavaRxToFs2.scala
  ethclient/src/test/scala/fluence/ethclient/ContractSpec.scala
  node/src/main/scala/fluence/node/ExecIO.scala
  node/src/main/scala/fluence/node/FluenceNode.scala
  project/SbtCommons.scala
Labels: ~general

#218 Fix rust integration issues
  vm/src/main/scala/fluence/vm/AsmleWasmVm.scala
  vm/src/main/scala/fluence/vm/ModuleInstance.scala
  vm/src/test/resources/wast/bad-allocation-function.wast
  vm/src/test/resources/wast/counter-copy.wast
  vm/src/test/resources/wast/counter.wast
  vm/src/test/resources/wast/mul.wast
  vm/src/test/resources/wast/no-getMemory.wast
  vm/src/test/resources/wast/simple-array-mutation.wast
  vm/src/test/resources/wast/simple-array-returning.wast
  vm/src/test/resources/wast/simple-string-passing.wast
  vm/src/test/resources/wast/sum-copy.wast
  vm/src/test/resources/wast/sum-with-trap.wast
  vm/src/test/resources/wast/sum.wast
  vm/src/test/scala/fluence/vm/WasmVmSpec.scala
Labels: enhancement

#220 Js client string support
  .travis.yml
  js-client/README.md
  js-client/package.json
  js-client/src/Result.ts
  js-client/src/TendermintClient.ts
  js-client/src/examples/CustomCommands.ts
  js-client/src/examples/DbClient.ts
  js-client/src/examples/IncrementAndMultiply.ts
  js-client/src/examples/QuotationClient.ts
  js-client/src/utils.ts
  js-client/verify.md
  statemachine/src/main/scala/fluence/statemachine/tx/FunctionCallDescription.scala
  statemachine/src/main/scala/fluence/statemachine/tx/VmOperationInvoker.scala
Labels: ~browser client, ~consensus

#221 Fix vm counter
  build.sbt
  vm/examples/counter/src/main/rust/lib.rs
  vm/examples/counter/src/main/rust/memory_manager.rs
  vm/examples/llamadb/src/main/rust/lib.rs
  vm/examples/sqldb/Cargo.toml
  vm/examples/sqldb/src/main/rust/lib.rs
  vm/examples/sqldb/src/main/rust/sql_db.rs
  vm/examples/sqldb/src/main/scala/fluence/vm/examples/SqlDbRunner.scala
Labels: ~virtual machine

#222 Run Docker container with healthchecks
  build.sbt
  node/src/main/scala/fluence/node/DockerIO.scala
  node/src/main/scala/fluence/node/ExecIO.scala
  node/src/main/scala/fluence/node/FluenceNode.scala
  project/SbtCommons.scala
Labels: enhancement, ~general

#226 Solvers pool
  build.sbt
  node/src/main/scala/fluence/node/DockerIO.scala
  node/src/main/scala/fluence/node/FluenceNode.scala
  node/src/main/scala/fluence/node/HealthCheckConfig.scala
  node/src/main/scala/fluence/node/Solver.scala
  node/src/main/scala/fluence/node/SolverHealth.scala
  node/src/main/scala/fluence/node/SolverParams.scala
  node/src/main/scala/fluence/node/SolversPool.scala
  project/SbtCommons.scala
Labels: enhancement, ~general

#227 Switch to byte array parameter
  statemachine/src/main/scala/fluence/statemachine/tx/FunctionCallDescription.scala
  statemachine/src/main/scala/fluence/statemachine/tx/VmOperationInvoker.scala
  statemachine/src/main/scala/fluence/statemachine/util/HexCodec.scala
  vm/examples/llamadb/src/main/scala/fluence/vm/examples/LlamaDbRunner.scala
  vm/src/main/scala/fluence/vm/AsmleWasmVm.scala
  vm/src/main/scala/fluence/vm/WasmVm.scala
  vm/src/test/resources/wast/counter-copy.wast
  vm/src/test/resources/wast/counter.wast
  vm/src/test/resources/wast/mul.wast
  vm/src/test/resources/wast/simple-array-mutation.wast
  vm/src/test/resources/wast/simple-array-returning.wast
  vm/src/test/resources/wast/sum-copy.wast
  vm/src/test/resources/wast/sum.wast
  vm/src/test/scala/fluence/vm/AsmleWasmVmSpec.scala
Labels: enhancement, ~virtual machine

#239 Todo list with delete
  js-client/src/examples/fluence-sqldb/.gitignore
  js-client/src/examples/fluence-sqldb/index.html
  js-client/src/examples/fluence-sqldb/index.ts
  js-client/src/examples/fluence-sqldb/webpack.config.js
  js-client/src/examples/fluence-streamr/index.js
  js-client/src/examples/todo-list/index.js
Labels: ~browser client
