Repository fluencelabs/nox, pull requests merged in 2018-11, with the labels that each got.

#270 Avoid calling allocation function from Wasm with null size
  vm/src/main/scala/fluence/vm/AsmleWasmVm.scala
Labels: enhancement

#263 Rust sdk
  .travis.yml
  sdk/rust/Cargo.toml
  sdk/rust/README.md
  sdk/rust/rustfmt.toml
  sdk/rust/src/lib.rs
  sdk/rust/src/memory/errors.rs
  sdk/rust/src/memory/mod.rs
  vm/examples/counter/Cargo.toml
  vm/examples/counter/src/main/rust/counter.rs
  vm/examples/counter/src/main/rust/lib.rs
  vm/examples/counter/src/main/rust/memory_manager.rs
  vm/examples/counter/src/main/scala/fluence/vm/examples/CounterRunner.scala
  vm/examples/llamadb/Cargo.toml
  vm/examples/llamadb/src/main/rust/lib.rs
  vm/examples/llamadb/src/main/rust/tests.rs
Labels: ~virtual machine

#273 Publisher console utility
  publisher/Cargo.toml
  publisher/Deployer.abi
  publisher/README.md
  publisher/src/main.rs
  publisher/src/publisher.rs
  statemachine/docker/examples/vmcode-llamadb/llama_db.wasm
Labels: ~consensus

#285 Use memory region for hash mismatch dispute & query results
  docs/protocol.md
  docs/protocol/batch_validation.go
  docs/protocol/byte_region.go
  docs/protocol/client.go
  docs/protocol/merkle_proof.go
  docs/protocol/realtime.go
  docs/protocol/swarm.go
  docs/protocol/vm.go
Labels: research

#281 Publisher integration tests
  .travis.yml
  bootstrap/README.md
  bootstrap/package.json
  bootstrap/scripts/compile_sol.js
  bootstrap/scripts/generate_java_wrapper.sh
  publisher/Deployer.abi
  publisher/README.md
  publisher/build.rs
  publisher/scripts/swarm-simulation.js
  publisher/src/main.rs
  publisher/src/publisher.rs
Labels: ~external storage

#287 Wasm logger
  .travis.yml
  build.sbt
  sdk/rust/Cargo.toml
  sdk/rust/src/lib.rs
  sdk/rust/src/logger/mod.rs
  statemachine/docker/examples/vmcode-llamadb/llama_db.wasm
  statemachine/docker/solver/sm.config
  vm/examples/llamadb/Cargo.toml
  vm/examples/llamadb/src/main/rust/lib.rs
  vm/examples/llamadb/src/main/rust/tests.rs
  vm/examples/llamadb/src/main/scala/fluence/vm/examples/LlamaDbRunner.scala
  vm/src/main/resources/reference.conf
  vm/src/main/scala/fluence/vm/WasmVm.scala
  vm/src/main/scala/fluence/vm/config/VmConfig.scala
Labels: enhancement, ~virtual machine

#289 Add solver
  .travis.yml
  cli/Cargo.toml
  cli/README.md
  cli/build.rs
  cli/scripts/swarm-simulation.js
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/status.rs
  cli/src/utils.rs
  cli/src/whitelist.rs
  publisher/src/main.rs
  publisher/src/publisher.rs
Labels: ~CLI

#293 Download code from swarm
  .travis.yml
  build.sbt
  cli/scripts/swarm-simulation.js
  cli/src/register.rs
  externalstorage/src/main/scala/fluence/swarm/SwarmClient.scala
  externalstorage/src/test/scala/fluence/swarm/SwarmClientIntegrationSpec.scala
  node/src/main/resources/reference.conf
  node/src/main/scala/fluence/node/AddCodeApp.scala
  node/src/main/scala/fluence/node/ConfigOps.scala
  node/src/main/scala/fluence/node/MasterNode.scala
  node/src/main/scala/fluence/node/MasterNodeApp.scala
  node/src/main/scala/fluence/node/NodeConfig.scala
  node/src/main/scala/fluence/node/eth/DeployerContract.scala
  node/src/main/scala/fluence/node/solvers/CodeManager.scala
  node/src/main/scala/fluence/node/tendermint/ClusterData.scala
  node/src/main/scala/fluence/node/tendermint/KeysPath.scala
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
  project/SbtCommons.scala
  statemachine/src/main/scala/fluence/statemachine/ServerRunner.scala
  vm/src/main/scala/fluence/vm/WasmVm.scala
  vm/src/main/scala/fluence/vm/config/VmConfig.scala
Labels: ~external storage
