Repository fluencelabs/nox, pull requests merged in 2019-01, with the labels that each got.

#328 Specify git tags for dependencies
  cli/Cargo.toml
Labels: tech debt

#326 Generate smart contract API in Rust
  cli/Cargo.toml
  cli/src/contract_func.rs
  cli/src/contract_status/app.rs
  cli/src/contract_status/cluster.rs
  cli/src/contract_status/mod.rs
  cli/src/contract_status/node.rs
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/utils.rs
Labels: enhancement

#327 move deploy logic to the main repo
  tools/deploy/README.md
  tools/deploy/fabfile.py
  tools/deploy/scripts/compose.sh
  tools/deploy/scripts/node.yml
  tools/deploy/scripts/parity.yml
  tools/deploy/scripts/swarm.yml
  tools/run/compose.sh
  tools/run/docker-compose.yml
  tools/run/parity.yml
Labels: enhancement, ~general

#329 Wait sync
  ethclient/src/main/scala/fluence/ethclient/EthClient.scala
  node/src/main/scala/fluence/node/MasterNodeApp.scala
  tools/deploy/scripts/compose.sh
Labels: enhancement

#330 Rename Solver to Worker
  build.sbt
  cli/README.md
  cli/src/main.rs
  cli/src/register.rs
  ethclient/src/main/scala/fluence/ethclient/helpers/Web3jConverters.scala
  monitoring/README.md
  monitoring/src/nodeStatus.ts
  node/README.md
  node/src/main/resources/reference.conf
  node/src/main/scala/fluence/node/Configuration.scala
  node/src/main/scala/fluence/node/MasterNode.scala
  node/src/main/scala/fluence/node/MasterNodeApp.scala
  node/src/main/scala/fluence/node/StatusAggregator.scala
  node/src/main/scala/fluence/node/config/MasterConfig.scala
  node/src/main/scala/fluence/node/solvers/SolversPool.scala
  node/src/main/scala/fluence/node/tendermint/ClusterData.scala
  node/src/main/scala/fluence/node/tendermint/Validator.scala
  node/src/main/scala/fluence/node/workers/CodeManager.scala
  node/src/main/scala/fluence/node/workers/HealthCheckConfig.scala
  node/src/main/scala/fluence/node/workers/Worker.scala
  node/src/main/scala/fluence/node/workers/WorkerImage.scala
  node/src/main/scala/fluence/node/workers/WorkerInfo.scala
  node/src/main/scala/fluence/node/workers/WorkerParams.scala
  node/src/main/scala/fluence/node/workers/WorkerResponse.scala
  node/src/main/scala/fluence/node/workers/WorkersPool.scala
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
  statemachine/docker/worker/run.sh
  statemachine/src/main/scala/fluence/statemachine/AbciHandler.scala
  statemachine/src/main/scala/fluence/statemachine/state/Committer.scala
  statemachine/src/main/scala/fluence/statemachine/tx/TxStateDependentChecker.scala
  statemachine/src/main/scala/fluence/statemachine/tx/VmOperationInvoker.scala
  tools/monitoring/grafana/provisioning/dashboards/local_cluster.json
Labels: tech debt

#331 Switch to nel
  statemachine/src/main/resources/reference.conf
  statemachine/src/main/scala/fluence/statemachine/ServerRunner.scala
  vm/src/it/scala/fluence/vm/CounterIntegrationTest.scala
  vm/src/it/scala/fluence/vm/LlamadbIntegrationTest.scala
  vm/src/main/scala/fluence/vm/WasmVm.scala
  vm/src/test/scala/fluence/vm/AsmbleWasmVmSpec.scala
  vm/src/test/scala/fluence/vm/WasmVmSpec.scala
Labels: enhancement

#332 Able to deploy locally with parity node in dev mode
  bootstrap/unlock-keys.js
  tools/deploy/README.md
  tools/deploy/fabfile.py
  tools/deploy/scripts/compose.sh
  tools/deploy/scripts/deploy-contract.js
  tools/deploy/scripts/node.yml
  tools/deploy/scripts/parity.yml
Labels: enhancement

#324 Change some comments in contracts for better readability
  bootstrap/contracts/Deployer.sol
  bootstrap/contracts/Network.sol
Labels: documentation, enhancement

#338 Fix timeouts format in Tendermint config file & reduce timeout in tests
  node/src/main/resources/docker/tendermint/config/default_config.toml
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
Labels: bug

#336 Refactor travis tests
  .travis.yml
  vm/examples/counter/Cargo.lock
  vm/examples/llamadb/Cargo.lock
Labels: enhancement

#335 Update contract status for a browser for new contract API
  bootstrap/contracts/Network.sol
  bootstrap/test/FluenceContractTest.js
  bootstrap/test/PinningTest.js
  bootstrap/test/Utils.js
  cli/src/contract_status/app.rs
  cli/src/contract_status/mod.rs
  cli/src/register.rs
  ethclient/src/main/java/fluence/ethclient/Network.java
  monitoring/src/app.ts
  monitoring/src/cluster.ts
  monitoring/src/contractStatus.ts
  monitoring/src/fluence.ts
  monitoring/src/node.ts
  tools/deploy/fabfile.py
  tools/deploy/scripts/compose.sh
  tools/deploy/scripts/deploy-contract.js
  tools/deploy/scripts/node.yml
Labels: ~browser client

#343 Ethclient refactoring
  build.sbt
  ethclient/src/main/java/fluence/ethclient/Network.java
  ethclient/src/main/scala/fluence/ethclient/EthClient.scala
  ethclient/src/main/scala/fluence/ethclient/EthClientApp.scala
  ethclient/src/main/scala/fluence/ethclient/data/Block.scala
  ethclient/src/main/scala/fluence/ethclient/data/Log.scala
  ethclient/src/main/scala/fluence/ethclient/data/Transaction.scala
  ethclient/src/main/scala/fluence/ethclient/helpers/JavaRxToFs2.scala
  ethclient/src/main/scala/fluence/ethclient/helpers/RemoteCallOps.scala
  ethclient/src/main/scala/fluence/ethclient/helpers/Web3jConverters.scala
  ethclient/src/test/scala/fluence/ethclient/ClusterContractSpec.scala
  node/src/main/scala/fluence/node/eth/FluenceContract.scala
  node/src/main/scala/fluence/node/tendermint/ClusterData.scala
  project/SbtCommons.scala
Labels: ~external storage

#341 Pinning, app deletion, clusters list in status
  bootstrap/contracts/Deployer.sol
  bootstrap/contracts/Network.sol
  bootstrap/test/AppDeleteTest.js
  bootstrap/test/FluenceContractTest.js
  bootstrap/test/PinningTest.js
  bootstrap/test/Utils.js
  cli/src/contract_status/app.rs
  cli/src/contract_status/mod.rs
  cli/src/contract_status/status.rs
  cli/src/delete_app.rs
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/utils.rs
  ethclient/src/main/java/fluence/ethclient/Network.java
  ethclient/src/main/scala/fluence/ethclient/helpers/Web3jConverters.scala
  ethclient/src/test/scala/fluence/ethclient/ClusterContractSpec.scala
  node/src/main/scala/fluence/node/MasterNode.scala
  node/src/main/scala/fluence/node/eth/FluenceContract.scala
  node/src/main/scala/fluence/node/tendermint/ClusterData.scala
  node/src/main/scala/fluence/node/tendermint/json/Genesis.scala
Labels: ~CLI, ~general

#344 Add integration test with infrastructure
  bootstrap/contracts/Deployer.sol
  bootstrap/package-lock.json
  bootstrap/package.json
  bootstrap/truffle.js
  cli/Cargo.lock
  cli/Cargo.toml
  cli/README.md
  cli/src/check.rs
  cli/src/contract_func.rs
  cli/src/contract_status/app.rs
  cli/src/contract_status/cluster.rs
  cli/src/contract_status/mod.rs
  cli/src/contract_status/node.rs
  cli/src/contract_status/status.rs
  cli/src/credentials.rs
  cli/src/delete_app.rs
  cli/src/lib.rs
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/types.rs
  cli/src/utils.rs
  cli/tests/delete_app.rs
  cli/tests/pinning.rs
  cli/tests/utils/mod.rs
  ethclient/src/main/java/fluence/ethclient/Network.java
Labels: ~CLI

#345 Worker rpc
  ethclient/src/main/scala/fluence/ethclient/EthClient.scala
  ethclient/src/main/scala/fluence/ethclient/EthClientApp.scala
  node/src/main/scala/fluence/node/Configuration.scala
  node/src/main/scala/fluence/node/MasterNodeApp.scala
  node/src/main/scala/fluence/node/config/MasterConfig.scala
  node/src/main/scala/fluence/node/eth/EthereumRpcConfig.scala
  node/src/main/scala/fluence/node/workers/Worker.scala
  node/src/main/scala/fluence/node/workers/WorkerRpc.scala
  node/src/main/scala/fluence/node/workers/WorkersPool.scala
  tools/deploy/scripts/just_kovan.sh
Labels: ~general

#351 Deploy updates
  js-client/package.json
  js-client/src/Signer.ts
  js-client/src/fluence.ts
  js-client/src/test/signer.spec.ts
  tools/deploy/fabfile.py
  tools/deploy/scripts/compose.sh
  tools/deploy/scripts/contract.txt
  tools/deploy/scripts/kovan-compose.sh
Labels: tech debt

#348 Remove workers upon receiving AppDeleted in Fluence Node
  bootstrap/contracts/Deployer.sol
  build.sbt
  cli/src/register.rs
  ethclient/src/main/java/fluence/ethclient/Network.java
  ethclient/src/main/scala/fluence/ethclient/helpers/Web3jConverters.scala
  js-client/package-lock.json
  js-client/src/Signer.ts
  js-client/src/test/signer.spec.ts
  node/src/main/scala/fluence/node/Configuration.scala
  node/src/main/scala/fluence/node/MasterNode.scala
  node/src/main/scala/fluence/node/MasterNodeApp.scala
  node/src/main/scala/fluence/node/StatusAggregator.scala
  node/src/main/scala/fluence/node/config/MasterConfig.scala
  node/src/main/scala/fluence/node/docker/DockerIO.scala
  node/src/main/scala/fluence/node/docker/DockerParams.scala
  node/src/main/scala/fluence/node/eth/App.scala
  node/src/main/scala/fluence/node/eth/Cluster.scala
  node/src/main/scala/fluence/node/eth/FluenceContract.scala
  node/src/main/scala/fluence/node/eth/WorkerNode.scala
  node/src/main/scala/fluence/node/tendermint/ClusterData.scala
  node/src/main/scala/fluence/node/tendermint/PersistentPeer.scala
  node/src/main/scala/fluence/node/tendermint/config/GenesisConfig.scala
  node/src/main/scala/fluence/node/tendermint/config/WorkerConfigWriter.scala
  node/src/main/scala/fluence/node/tendermint/json/Genesis.scala
  node/src/main/scala/fluence/node/tendermint/json/NodeInfo.scala
  node/src/main/scala/fluence/node/tendermint/json/Validator.scala
  node/src/main/scala/fluence/node/tendermint/json/ValidatorKey.scala
  node/src/main/scala/fluence/node/workers/CodeManager.scala
  node/src/main/scala/fluence/node/workers/Worker.scala
  node/src/main/scala/fluence/node/workers/WorkerHealth.scala
  node/src/main/scala/fluence/node/workers/WorkerParams.scala
  node/src/main/scala/fluence/node/workers/WorkerResponse.scala
  node/src/main/scala/fluence/node/workers/WorkerRpc.scala
  node/src/main/scala/fluence/node/workers/WorkersPool.scala
  node/src/test/scala/fluence/node/DockerSetup.scala
  node/src/test/scala/fluence/node/GanacheSetup.scala
  node/src/test/scala/fluence/node/Integration.scala
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
  node/src/test/scala/fluence/node/OsSetup.scala
  node/src/test/scala/fluence/node/TendermintSetup.scala
Labels: enhancement, ~general

#352 Fix TENDERMINT_KEY regex
  tools/deploy/scripts/compose.sh
Labels: enhancement

#354 Create config directory before downloading code
  node/src/main/scala/fluence/node/MasterNode.scala
  node/src/main/scala/fluence/node/tendermint/config/WorkerConfigWriter.scala
Labels: bug

#355 Remove trailing zeros from container names
  node/src/main/scala/fluence/node/workers/WorkerParams.scala
Labels: bug

#357 Fix deploy scripts
  node/src/main/resources/docker/tendermint/config/default_config.toml
  tools/deploy/fabfile.py
  tools/deploy/scripts/compose.sh
  tools/deploy/scripts/deploy-contract.js
  tools/deploy/scripts/parity.yml
Labels: bug, tech debt

#360 move gitignore from global scope to sdk project folder
  .gitignore
  sdk/rust/.gitignore
Labels: enhancement

#356 Refactor clap arguments usage to be more DRY
  cli/README.md
  cli/src/command.rs
  cli/src/contract_status/mod.rs
  cli/src/delete_app.rs
  cli/src/lib.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/tests/pinning.rs
  cli/tests/utils/mod.rs
  tools/deploy/scripts/compose.sh
Labels: enhancement, tech debt, ~CLI

#358 Migrate from Box<Error> to failure
  cli/Cargo.lock
  cli/Cargo.toml
  cli/src/command.rs
  cli/src/contract_func.rs
  cli/src/contract_status/app.rs
  cli/src/contract_status/cluster.rs
  cli/src/contract_status/mod.rs
  cli/src/contract_status/node.rs
  cli/src/contract_status/status.rs
  cli/src/delete_app.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/types.rs
  cli/src/utils.rs
  cli/tests/utils/mod.rs
Labels: enhancement, tech debt, ~CLI

#359 Implement deleteNode in smart contract
  bootstrap/contracts/Deployer.sol
  bootstrap/test/AppDeleteTest.js
  bootstrap/test/NodeDeleteTest.js
  bootstrap/test/Utils.js
  ethclient/src/main/java/fluence/ethclient/Network.java
Labels: ~general

#363 Implement node deletion in CLI
  cli/src/command.rs
  cli/src/delete_app.rs
  cli/src/delete_node.rs
  cli/src/lib.rs
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/tests/delete_app.rs
  cli/tests/delete_node.rs
  cli/tests/pinning.rs
  cli/tests/utils/mod.rs
Labels: ~CLI

#365 Fluence guides
  docs/guides/README.md
  docs/guides/backend.md
  docs/guides/frontend.md
  docs/guides/miner.md
  tools/deploy/fabfile.py
  tools/deploy/scripts/compose.sh
  tools/deploy/scripts/kovan-compose.sh
  tools/deploy/scripts/multiple-node.yml
  tools/deploy/scripts/node.yml
  tools/run/docker-compose.yml
Labels: documentation

#367 Remove positional args in CLI
  build.sbt
  cli/README.md
  cli/src/command.rs
  cli/src/delete_app.rs
  cli/src/delete_node.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/tests/delete_app.rs
  cli/tests/delete_node.rs
  cli/tests/pinning.rs
  cli/tests/utils/mod.rs
  docs/guides/miner.md
  node/README.md
  project/SbtCommons.scala
  tools/deploy/scripts/compose.sh
Labels: ~CLI

#368 Use tendermint node_id for node_address generation
  cli/README.md
  cli/src/command.rs
  cli/src/contract_status/mod.rs
  cli/src/register.rs
  cli/src/types.rs
  cli/tests/utils/mod.rs
  tools/deploy/fabfile.py
  tools/deploy/scripts/compose.sh
Labels: bug, ~CLI

#369 Delete app id in nodes in Fluence contract
  bootstrap/contracts/Deployer.sol
  bootstrap/scripts/compile_sol.js
  bootstrap/test/AppDeleteTest.js
  bootstrap/test/FluenceContractTest.js
  bootstrap/test/NodeDeleteTest.js
  bootstrap/test/PinningTest.js
  bootstrap/test/Utils.js
  cli/Cargo.toml
  fluence-js/src/examples/fluence-sqldb/index.ts
  monitoring/README.md
  monitoring/package.json
  tools/deploy/scripts/deploy-contract.js
Labels: bug

#370 Implement loading secret from JSON keystore
  cli/Cargo.lock
  cli/Cargo.toml
  cli/src/command.rs
  cli/src/main.rs
Labels: ~CLI

#372 Devnet Overview
  bootstrap/README.md
  devnet.md
  tools/run/README.md
  tools/run/blockchain.sh
  tools/run/cleanup.sh
  tools/run/compose.sh
  tools/run/docker-compose.yml
Labels: documentation

#371 Sdk/improve backend guide
  docs/guides/backend.md
  sdk/rust/README.md
Labels: documentation

#373 Deploy updates
  fluence-js/src/examples/fluence-sqldb/index.ts
  monitoring/src/fluence.ts
  tools/deploy/scripts/compose.sh
  tools/deploy/scripts/contract.txt
  tools/deploy/scripts/swarm.yml
Labels: tech debt

#374 Vm/hello world example
  build.sbt
  vm/examples/hello-user/Cargo.lock
  vm/examples/hello-user/Cargo.toml
  vm/examples/hello-user/rust-toolchain
  vm/examples/hello-user/src/lib.rs
  vm/src/it/scala/fluence/vm/HelloUserIntegrationTest.scala
Labels: documentation

#379 Decouple tests settings from py file to csv
  bench/vm/bencher/README.md
  bench/vm/bencher/main.py
  bench/vm/bencher/project/BenchTestGenerator.py
  bench/vm/bencher/project/TestDescriptor.py
  bench/vm/bencher/project/VMDescriptor.py
  bench/vm/bencher/project/WasmVMBencher.py
  bench/vm/bencher/project/__init__.py
  bench/vm/bencher/project/settings.py
  bench/vm/bencher/settings.py
  bench/vm/bencher/test_settings/jit_vs_interpreters.csv
Labels: research

#380 rename `fluence-js` to `fluence`
  docs/guides/frontend.md
  fluence-js/README.md
  fluence-js/package-lock.json
  fluence-js/package.json
  fluence-js/src/examples/CustomCommands.ts
  fluence-js/src/examples/IncrementAndMultiply.ts
  fluence-js/src/examples/fluence-sqldb/index.ts
  fluence-js/src/examples/fluence-sqldb/package.json
  fluence-js/src/examples/fluence-streamr/README.md
  fluence-js/src/examples/fluence-streamr/index.js
  fluence-js/src/examples/fluence-streamr/package.json
  fluence-js/src/examples/todo-list/index.js
  fluence-js/src/examples/todo-list/package.json
  fluence-js/src/fluence.ts
  monitoring/package-lock.json
  monitoring/package.json
Labels: ~browser client

#375 Wait for events after submitting a transaction
  bootstrap/contracts/Deployer.sol
  cli/Cargo.lock
  cli/Cargo.toml
  cli/src/command.rs
  cli/src/contract_func.rs
  cli/src/contract_status/app.rs
  cli/src/contract_status/cluster.rs
  cli/src/contract_status/mod.rs
  cli/src/contract_status/node.rs
  cli/src/contract_status/status.rs
  cli/src/delete_app.rs
  cli/src/delete_node.rs
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/src/utils.rs
  cli/tests/delete_app.rs
  cli/tests/delete_node.rs
  cli/tests/pinning.rs
  cli/tests/utils/mod.rs
Labels: ~CLI

#381 [WIP] Make app_id uint64
  bootstrap/contracts/Deployer.sol
  bootstrap/contracts/Network.sol
  bootstrap/scripts/compile_sol.js
  bootstrap/test/AppDeleteTest.js
  bootstrap/test/FluenceContractTest.js
  cli/src/contract_status/app.rs
  cli/src/delete_app.rs
  cli/src/main.rs
  cli/src/publisher.rs
  cli/src/register.rs
  cli/tests/delete_app.rs
  cli/tests/pinning.rs
  cli/tests/utils/mod.rs
  ethclient/src/main/java/fluence/ethclient/Network.java
  ethclient/src/main/scala/fluence/ethclient/helpers/Web3jConverters.scala
  node/src/main/scala/fluence/node/eth/FluenceContract.scala
  node/src/main/scala/fluence/node/eth/NodeEth.scala
  node/src/main/scala/fluence/node/eth/NodeEthEvent.scala
  node/src/main/scala/fluence/node/eth/NodeEthState.scala
  node/src/main/scala/fluence/node/eth/state/App.scala
  node/src/main/scala/fluence/node/workers/WorkerParams.scala
  node/src/main/scala/fluence/node/workers/WorkersPool.scala
  node/src/main/scala/fluence/node/workers/health/RunningWorkerInfo.scala
  node/src/main/scala/fluence/node/workers/tendermint/config/GenesisConfig.scala
  node/src/main/scala/fluence/node/workers/tendermint/config/WorkerConfigWriter.scala
  node/src/test/scala/fluence/node/MasterNodeIntegrationSpec.scala
  node/src/test/scala/fluence/node/eth/FluenceContractTestOps.scala
Labels: enhancement, ~general

#377 Show contract state as an interactive command line table
  cli/Cargo.lock
  cli/Cargo.toml
  cli/src/contract_status/app.rs
  cli/src/contract_status/mod.rs
  cli/src/contract_status/status.rs
  cli/src/contract_status/ui/async_keys.rs
  cli/src/contract_status/ui/mod.rs
  cli/src/contract_status/ui/rich_status.rs
  cli/src/main.rs
  cli/tests/pinning.rs
Labels: enhancement, ~CLI

#384 Bump cli to 0.1.2
  cli/Cargo.lock
  cli/Cargo.toml
Labels: ~CLI

#382 Mining guide: pinning & node removal
  cli/README.md
  docs/guides/frontend.md
  docs/guides/miner.md
Labels: documentation

#386 Change contract address
  cli/src/contract_func.rs
  fluence-js/src/examples/fluence-sqldb/index.ts
  tools/deploy/scripts/contract.txt
Labels: ~general

#387 update versions of js libs due to the new contract
  fluence-js/package-lock.json
  fluence-js/package.json
  fluence-js/src/examples/fluence-sqldb/index.ts
  fluence-js/src/examples/fluence-sqldb/package.json
  monitoring/package-lock.json
  monitoring/package.json
Labels: ~browser client

#385 Rust sdk version 0.0.7
  .travis.yml
  sdk/rust/Cargo.toml
  sdk/rust/src/export_allocator/mod.rs
  sdk/rust/src/lib.rs
  sdk/rust/src/logger/mod.rs
  sdk/rust/src/memory/errors.rs
  sdk/rust/src/memory/mod.rs
  vm/examples/README.md
  vm/examples/counter/Cargo.lock
  vm/examples/counter/Cargo.toml
  vm/examples/counter/src/lib.rs
  vm/examples/fleth/Cargo.lock
  vm/examples/fleth/Cargo.toml
  vm/examples/fleth/src/lib.rs
  vm/examples/hello-user/Cargo.lock
  vm/examples/hello-user/Cargo.toml
  vm/examples/hello-user/src/lib.rs
  vm/examples/llamadb/Cargo.lock
  vm/examples/llamadb/Cargo.toml
  vm/examples/llamadb/src/lib.rs
  vm/examples/llamadb/src/tests.rs
  vm/src/it/scala/fluence/vm/AppIntegrationTest.scala
  vm/src/it/scala/fluence/vm/CounterIntegrationTest.scala
  vm/src/it/scala/fluence/vm/HelloUserIntegrationTest.scala
  vm/src/it/scala/fluence/vm/LlamadbIntegrationTest.scala
Labels: enhancement, ~vm_sdk
